plugins {
    id("org.jetbrains.kotlin.jvm")
    application
}

version = "1.0.0"

repositories {
    mavenCentral()
    jcenter()
}

dependencies {
    implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8")
    implementation("com.beust:klaxon:3.0.1") //5.2
}

application {
    mainClassName = "GeneratorKt"
}

tasks.build {
    finalizedBy(tasks.run) //execute godot api classes generation after building the api_classes_generator project
}

tasks.clean {
    doFirst {
        delete("${rootDir}/wrapper/godot-library/src/main/kotlin/godot/generated") //delete classes generated by this generator
    }
}