package godot.entrygenerator.model

const val REGISTER_CLASS_ANNOTATION = "godot.annotation.RegisterClass"
const val REGISTER_FUNCTION_ANNOTATION = "godot.annotation.RegisterFunction"
const val REGISTER_PROPERTY_ANNOTATION = "godot.annotation.RegisterProperty"


const val REGISTER_CLASS_ANNOTATION_TOOL_ARGUMENT = "isTool"
const val REGISTER_FUNCTION_ANNOTATION_RPC_MODE_ARGUMENT = "rpcMode"
const val REGISTER_PROPERTY_ANNOTATION_VISIBLE_IN_EDITOR_ARGUMENT = "visibleInEditor"
const val REGISTER_PROPERTY_ANNOTATION_RPC_MODE_ARGUMENT = "rpcMode"


const val RANGE_ANNOTATION_START_ARGUMENT = "start"
const val RANGE_ANNOTATION_END_ARGUMENT = "end"
const val RANGE_ANNOTATION_STEP_ARGUMENT = "step"
const val RANGE_ANNOTATION_OR_ARGUMENT = "or"
const val EXP_EASING_ANNOTATION_ATTENUATION_ARGUMENT = "attenuation"
const val EXP_EASING_ANNOTATION_INOUT_ARGUMENT = "inout"
const val LENGTH_ANNOTATION_LENGTH_ARGUMENT = "length"
const val FILE_AND_DIR_ANNOTATION_EXTENSIONS_ARGUMENT = "extensions"
const val FILE_AND_DIR_ANNOTATION_GLOBAL_ARGUMENT = "global"
const val INT_FLAG_ANNOTATION_NAMES_ARGUMENT = "names"
