@ECHO off

SET CURRENT_PATH=%0/../


IF NOT DEFINED API_GENERATOR_PATH SET API_GENERATOR_PATH="tools/api_classes_generator"
IF NOT DEFINED API_GENERATOR_TASKS SET API_GENERATOR_TASKS="run"

IF NOT DEFINED WRAPPER_PATH SET WRAPPER_PATH="wrapper"
IF NOT DEFINED WRAPPER_TASKS SET WRAPPER_TASKS="publish"

IF NOT DEFINED ENTRY_GENERATOR_PATH SET ENTRY_GENERATOR_PATH="tools/entry_generator"
IF NOT DEFINED ENTRY_GENERATOR_TASKS SET ENTRY_GENERATOR_TASKS="build"

IF NOT DEFINED GRADLE_PLUGIN_PATH SET GRADLE_PLUGIN_PATH="tools/gradle_plugin"
IF NOT DEFINED GRADLE_PLUGIN_TASKS SET GRADLE_PLUGIN_TASKS="publish"

IF NOT DEFINED SAMPLES_PATH SET SAMPLES_PATH="samples/games/kotlin"
IF NOT DEFINED SAMPLES_TASKS SET SAMPLES_TASKS="build"



CALL :ExecuteGradle %API_GENERATOR_PATH%, %API_GENERATOR_TASKS%
CALL :ExecuteGradle %WRAPPER_PATH%, %WRAPPER_TASKS%
CALL :ExecuteGradle %ENTRY_GENERATOR_PATH%, %ENTRY_GENERATOR_TASKS%
CALL :ExecuteGradle %GRADLE_PLUGIN_PATH%, %GRADLE_PLUGIN_TASKS%
CALL :ExecuteGradle %SAMPLES_PATH%, %SAMPLES_TASKS%

EXIT /B 0


:ExecuteGradle
cd %~1
@ECHO on
call gradlew %~2
@ECHO off
cd %CURRENT_PATH%
EXIT /B 0