include(":wrapper")
include(":wrapper:godot-library")
include(":wrapper:godot-library-extension")
include(":tools:api-classes-generator")
include(":tools:entry-generator")
include(":tools:godot-gradle-plugin")
include(":tools:annotations")
include(":tools:godot-annotation-processor")
include(":tools:kotlin-compiler-plugin")
include(":tools:kotlin-compiler-native-plugin")

enableFeaturePreview("GRADLE_METADATA")
