{
  "formatVersion": "0.4",
  "component": {
    "url": "../../kotlin-godot-libraries/1.0.0/kotlin-godot-libraries-1.0.0.module",
    "group": "org.jetbrains.kotlin",
    "module": "kotlin-godot-libraries",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "4.10.2",
      "buildId": "st64rfmho5asznkgl4ngpp7cka"
    }
  },
  "variants": [
    {
      "name": "windows-api",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kotlin-godot-libraries.klib",
          "url": "kotlin-godot-libraries-windows-1.0.0.klib",
          "size": 23578603,
          "sha1": "e360e4951f625f675e913a7b23fb585cdeda0b87",
          "md5": "d22d2d7e9600efe3327914a88e37ad76"
        },
        {
          "name": "kotlin-godot-libraries-cinterop-GDNative.klib",
          "url": "kotlin-godot-libraries-windows-1.0.0-cinterop-GDNative.klib",
          "size": 789173,
          "sha1": "681916533c548439284da466e0a3dc18c37d204b",
          "md5": "f174603b34ad00febf47f00925d96dd1"
        }
      ]
    },
    {
      "name": "metadata-api",
      "attributes": {
        "artifactType": "jar",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../kotlin-godot-libraries-metadata/1.0.0/kotlin-godot-libraries-metadata-1.0.0.module",
        "group": "org.jetbrains.kotlin",
        "module": "kotlin-godot-libraries-metadata",
        "version": "1.0.0"
      }
    }
  ]
}
