{
  "formatVersion": "0.4",
  "component": {
    "url": "../../kotlin-godot-libraries-windows/1.0.0/kotlin-godot-libraries-windows-1.0.0.module",
    "group": "org.jetbrains.kotlin",
    "module": "kotlin-godot-libraries-windows",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "4.10.2",
      "buildId": "st64rfmho5asznkgl4ngpp7cka"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "artifactType": "jar",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "kotlin-godot-libraries-metadata-1.0.0.jar",
          "url": "kotlin-godot-libraries-metadata-1.0.0.jar",
          "size": 261,
          "sha1": "c60810a4a120c3157c68d8e7593d883de5811a5d",
          "md5": "5f1841ebaa836a4ef34fbc19453699e6"
        }
      ]
    }
  ]
}
